config/routes.rb
Rails.application.routes.draw do
  resources :offers
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'pages#dashboard'
  get 'success', to: 'pages#success'

  resources :offers do
      resources :bookings, only: [ :new, :create]
  end
  resources :bookings, only: [ :update ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :offer
  belongs_to :user
  validate :end_date_after_start_date
  validates :start_date, :end_date, :overlap => {:scope => "offer_id"}

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  validates :title, :item, :description, :location, presence: true
  validates :price_per_day, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :offers
  has_many :bookings

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:home, :index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password])
  end

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(offers_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)
    @offer = Offer.find(params[:offer_id])

    authorize @booking
    @booking.user = current_user
    @booking.offer = @offer
    if @booking.save
      redirect_to dashboard_path
    else
      render "offers/show"
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if params[:accept] == "accepted"
      @booking.status = true
      flash.notice = "Demande acceptée!"
    elsif params[:accept] == "declined"
      @booking.status = false
      flash.notice = "Demande refusée!"
    end
    @booking.save!
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = policy_scope(Offer)
    searching
    sorting
  end

  def show
    @offer = Offer.find(params[:id])
    authorize @offer
    @booking = Booking.new
    @bookings_dates = Booking.where(offer: @offer).map do |booking|
      {
        from: booking.start_date,
        to: booking.end_date,
      }
    end
  end

  def new
    @offer = Offer.new
    authorize @offer
  end

  def create
    @offer = Offer.new(offer_params)
    authorize @offer
    @offer.user = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def edit
    @offer = Offer.find(params[:id])
    authorize @offer
  end

  def update
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.update(offer_params)
    redirect_to offer_path(@offer)
  end

  def destroy
    @offer = Offer.find(params[:id])
    authorize @offer
    @offer.destroy
    redirect_to dashboard_path
  end

  private

  def searching

    if (params[:query] == "") & (params[:queryLocation] == "") & (params[:queryPrice] == "") & (params[:sort] == "")
      redirect_to offers_path
      flash.alert = "Recherche vide !"
    else
      @offers = Offer.all
    end

    if params[:query].present?
      sql_query = "title ILIKE :query OR item ILIKE :query"
      @offers = Offer.where(sql_query, query: "%#{params[:query]}%")
    end
    if params[:queryLocation].present?
      sql_query_location = "location ILIKE :queryLocation"
      @offers = @offers.where(sql_query_location, queryLocation: "%#{params[:queryLocation]}%")
    end
    if params[:queryPrice].present?
      sql_query_price = "price_per_day < :queryPrice"
      @offers = @offers.where(sql_query_price, queryPrice: params[:queryPrice])
    end

    flash.alert = "Désolé, aucun résultat ne correspond à cette recherche!" if @offers.count.zero?
  end

  def sorting
    searching
    case params[:sort]
    when "price-up"
      @offers = @offers.order(:price_per_day)
    when "price-down"
      @offers = @offers.order(:price_per_day).reverse
    end
  end

  def offer_params
    params.require(:offer).permit(:title, :item, :description, :price_per_day, :location, :start_date, :end_date, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def dashboard
    # @offers = policy_scope(Offer).where(user_id: current_user.id)
    # @bookings = policy_scope(Booking)
    # @offers_sent = []
    # policy_scope(Offer).each { |offer| @offers_sent << offer if offer.bookings.user == current_user }
    @offers = policy_scope(Booking).where(user_id: current_user.id).map { |b| b.offer }
    @bookings_received = []
    policy_scope(Booking).each do |booking|
      @bookings_received << booking if booking.offer.user == current_user
    end
    @offers_received = @bookings_received.map { |b| b.offer }
    if params[:sort] == "price-up"
      @offers = @offers.order(:price_per_day)
    elsif params[:sort] == "price-down"
      @offers = @offers.order(:price_per_day).reverse
    elsif params[:sort] == "location"
      @offers = @offers.order(:location)
    end
  end

  def success
  end

  def home
    @offers = Offer.last(6).reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def svg_tag(svg_name)
    render inline: Rails.root.join("app/assets/images/#{svg_name}").read
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameNShare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/offers/edit.html.erb
<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center my-3">
    <div class="col-10 col-md-8 col-lg-6">
      <h1>Edit</h1>

      <%= @offer.title %>

      <%= simple_form_for @offer do |f| %>
        <div class="form-inputs">
          <%= f.input :title %>
          <%= f.input :item %>
          <%= f.input :description %>
          <%= f.input :price_per_day, as: :integer %>
          <%= f.input :location %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>

        </div>
        <div class="d-flex justify-content-between">
          <div class="form-actions">
            <%= f.button :submit, "Envoyer", class: "btn btn-dark my-auto" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<div class="container">
  <div class="first-box px-0">
    <h1>Offres disponibles</h1>

    <div class="form-group">
      <%= form_tag offers_path, method: :get do %>
        <%= text_field_tag :query,
                          params[:query],
                          class: "form-control my-2",
                          placeholder: "Que cherchez-vous ?" %>
        <%= text_field_tag :queryLocation,
                          params[:queryLocation],
                          class: "form-control my-2",
                          placeholder: "Oussa ?" %>
        <%= number_field_tag :queryPrice,
                          params[:queryPrice],
                          min: 1,
                          max: 1000,
                          class: "form-control my-2",
                          placeholder: "Pour combien de pépettes max par jour ?" %>
        <div class="my-3">
          <%= submit_tag "Chercher", class: "btn btn-dark" %>
          <%= link_to "Reset", offers_path, class: "btn btn-dark" %>
        </div>

      <% end %>
    </div>

    <%= render "shared/sorting", offers: @offers %>

    <%= render "shared/simple_cards_index", offers: @offers.reverse %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container h-100">
  <div class="row h-100 justify-content-center align-items-center my-3">
    <div class="col-10 col-md-8 col-lg-6">
      <h2>Créer une annonce</h2>

      <%= simple_form_for @offer do |f| %>
        <div class="form-inputs">
              <%= f.input :title %>
              <%= f.input :item %>
              <%= f.input :description %>
              <%= f.input :price_per_day, as: :integer %>
              <%= f.input :location %>
              <%= f.input :start_date, as: :date, html5: true %>
              <%= f.input :end_date, as: :date, html5: true %>
              <%= f.input :photo, as: :file %>

        </div>
        <div class="d-flex justify-content-between">
          <div class="form-actions">
            <%= f.button :submit, "Envoyer", class: "btn btn-dark my-auto" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container">
  <div class="first-box px-0">
    <h2 class="offer-title d-flex"><%= @offer.title %></h2>
    <div class="container p-0 col-12 d-flex">
      <div class="p-0 col-5 d-flex img-div">
        <% if @offer.photo.attached? %>
          <%= cl_image_tag @offer.photo.key, width: 800, crop: :fill, class: "image_preview" %>
        <% else %>
          <%= image_tag "https://cdn.dribbble.com/users/1787323/screenshots/14113017/media/f8632f8c42e53263256b94e6e575c3df.png?compress=1&resize=800x600", class: "img-show", width: "100%" %>
        <% end %>
      </div>

      <div class="all-grey-info col-3 mx-3">
        <div class="grey-info d-flex row align-items-center">
          <i class="fas fa-user mx-2"></i>
          <div id="grey-info-text">
            <%= @offer.user.username %>
          </div>
        </div>
        <div class="grey-info d-flex row align-items-center">
          <i class="fas fa-map-marker-alt mx-2"></i>
          <div id="grey-info-text">
            <%= @offer.location %>
          </div>
        </div>

        <% if @offer.start_date %>
          <div class="grey-info d-flex row align-items-center">
            <i class="far fa-calendar-alt mx-2"></i>
              <div id="grey-info-text">
                <%= @offer.start_date.strftime('%d/%m/%Y') %>
              </div>
          </div>
        <% end %>
        <% if @offer.start_date %>
          <div class="grey-info d-flex row align-items-center">
            <i class="far fa-calendar-alt mx-2"></i>
            <div id="grey-info-text">
              <%= @offer.end_date.strftime('%d/%m/%Y') %>
            </div>
          </div>
        <% end %>
        <div class="grey-info d-flex row align-items-center">
          <i class="fas fa-gamepad mx-2"></i>
          <div id="grey-info-text">
            <%= @offer.item %>
          </div>
        </div>

      </div>

      <div class="booking-form">
        <% if !policy(@offer).edit? %>
          <div class="row m-0 justify-content-between" id="booking-form-div" data-bookings="<%= @bookings_dates.to_json %>">
            <%= simple_form_for [@offer, @booking] do |f| %>
              <%= f.input :start_date, label: false, as: :string, required: false, input_html: { id: "range_start", class: "d-none" } %>
              <%= f.input :end_date, label: false, as: :string, required: false, input_html: { id: "range_end", class: "d-none" } %>
              <div>
                <%= f.button :submit, "Je réserve", class: "btn btn-dark p-3 w-100" %>
              </div>

            <% end %>
          </div>
        <% end %>
      </div>

    </div>

    <div class="col-5 p-0">
      <% if policy(@offer).edit? %>
        <div class="row m-0 justify-content-between">
          <%= link_to "Modifier", edit_offer_path(@offer), class: "btn btn-dark p-3 my-4 mr-2 flex-fill" %>
          <%= link_to "Supprimer", offer_path(@offer), method: :delete, data: { confirm: "Etes-vous sûr de vouloir supprimer cette offre?" }, class: "btn btn-dark p-3 my-4 ml-2 flex-fill" %>
        </div>
      <% end %>
    </div>

    <div class="container description p-0 col-12 d-flex">
      <h4>Description</h5>
      <div>
        <%= @offer.description %>
      </div>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="first-box px-0">
    <h1>Mes annonces</h1>
    <%= render "shared/simple_cards_index", offers: Offer.where(user: current_user) %>
  </div>
  <div class="first-box px-0">
    <h1>Mes demandes envoyées</h1>
    <%= render "shared/reservation_cards", offers: @offers %>
  </div>
  <div class="first-box px-0">
    <h1>Mes demandes reçues</h1>
    <%= render "shared/reservation_cards", offers: @offers_received %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container col-10 d-flex align-items-center">
  <div class="first-box row justify-content-between">
    <div class="col-12 col-lg-6 d-flex-column py-4 px-0">
      <h1>Louez une console en quelques clics</h1>
      <p>Louez des jeux, des manettes pour une après-midi, une journée, une semaine et enjoy ! </p>

      <div class="form-group">
        <%= render "shared/form", offers: @offers %>
      </div>

    </div>
    <div class="col-lg-5 d-none d-lg-block align-items-center">
      <%= image_tag "https://cdn.dribbble.com/users/1787323/screenshots/14113017/media/6100e76fe57f7d61512b05e536820b94.png?compress=1&resize=800x600", width: "100%" %>
    </div>
  </div>
</div>

<div class="container col-10 d-flex align-items-center">
  <div class="first-box row">
    <div class="container p-0">
      <h2>Les dernières offres</h2>
      <%= render "shared/simple_cards_index", offers: @offers %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<div class="form-group">
  <%= form_tag offers_path, method: :get do %>
    <%= text_field_tag :query,
                        params[:query],
                        class: "form-control",
                        placeholder: "Que cherchez-vous ?" %>
    <%= submit_tag "Chercher", class: "btn btn-dark mt-3 " %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow-sm">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= svg_tag "gamepad-solid.svg"%>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to current_user.username, dashboard_path, class: "nav-link" %>
        </li>
       <li class="nav-item">
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else  %>
        <li class="nav-item">
          <%= link_to "Se connecter", "/users/sign_in", class: "nav-link" %>
        </li>
      <% end %>

      <li class="nav-item">
        <%= link_to "Toutes les offres", offers_path, class: "nav-link" %>
      </li>
      <%# <li class="nav-item"> %>
        <%#= link_to "Des questions ?", "#", class: "nav-link" %>
      <%# </li> %>
      </li>
      <li class="nav-item">
        <%= link_to "Louer ma console", new_offer_path, class: "btn btn-dark" %>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_reservation_cards.html.erb
<div class="row justify-content-left offers-container">
  <% offers.each do |offer| %>
    <% offer.bookings.each do |booking| %>
      <div class="card m-2" style="width: 18rem;">
        <% if offer.photo.attached? %>
          <%= cl_image_tag offer.photo.key, width: 400, class: "image_preview_dashboard" %>
        <% else %>
          <%= image_tag "https://cdn.dribbble.com/users/1787323/screenshots/14113017/media/f8632f8c42e53263256b94e6e575c3df.png?compress=1&resize=800x600", crop: :fill %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to offer.title.capitalize, offer_path(offer) %></h5>
          <p>Par: <%= booking.user.username %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Du: <%= booking.start_date.strftime('%d/%m/%Y') %></li>
          <li class="list-group-item">Au: <%= booking.end_date.strftime('%d/%m/%Y') %></li>
        </ul>
        <div class="card-body">
          <% if booking.status == true %>
            <h5>Acceptée!</h5>
          <% elsif booking.status == false %>
            <h5>Refusée</h5>
          <% elsif booking.offer.user_id == current_user.id %>
            <%= link_to "Accepter", booking_path(booking, params: {accept: "accepted"}), method: :patch, class: "btn btn-success" %>
            <%= link_to "Refuser", booking_path(booking, params: {accept: "declined"}), method: :patch, class: "btn btn-danger" %>
          <% else %>
            <h5>En attente de réponse...</h5>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_simple_cards_index.html.erb
<div  class="row justify-content-between offers-container">
  <% offers.each do |offer| %>
    <%= render "shared/simplecards", offer: offer %>
  <% end %>
</div>

app/views/shared/_simplecards.html.erb
  <div class="card_global col-10 col-md-6 col-lg-4 p-2">
    <div class="card-product">
      <% if offer.photo.attached? %>
        <%= cl_image_tag offer.photo.key, height: 300, width: 400, crop: :fill, class: "image_preview" %>
      <% else %>
        <%= image_tag "https://cdn.dribbble.com/users/1787323/screenshots/14113017/media/f8632f8c42e53263256b94e6e575c3df.png?compress=1&resize=800x600", width: 100 %>
      <% end %>
      <div class="card-product-infos align-self-center flex-fill bd-highlight">
        <h2><%= link_to offer.title.capitalize, offer_path(offer), data: {turbolinks: false } %></h2>
        <h5><%= offer.item.capitalize %></h5>
        <p><%= offer.location.capitalize %></p>
        <p><%= offer.price_per_day %>€ / jour</p>
      </div>
    </div>
  </div>

app/views/shared/_sorting.html.erb
<div class="sorting d-flex justify-content-end">
  <div class="justify-content-between">
    <%= link_to offers_path(query: params[:query] ? params[:query] : "", queryLocation: params[:queryLocation] ? params[:queryLocation] : "", queryPrice: params[:queryPrice] ? params[:queryPrice] : "", sort: "price-up") do %>
      <i class="fas fa-chevron-up"></i>
    <% end %>

    <%= link_to offers_path(query: params[:query] ? params[:query] : "", queryLocation: params[:queryLocation] ? params[:queryLocation] : "", queryPrice: params[:queryPrice] ? params[:queryPrice] : "", sort: "price-down") do %>
      <i class="fas fa-chevron-down"></i>
    <% end %>
    <i class="fas fa-euro-sign"></i>
  </div>
</div>